apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    name: avo2-proxy
    app: avo2-proxy-dev
  name: avo2-proxy-dev
spec:
  source:
    type: Git
    git:
      uri: https://github.com/viaacode/avo2-proxy.git

  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: openshift/Jenkinsfile
