apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    action_name: update-pubdate
    app: avo2-proxy
    ENV: qas
    template: cronjob
  name: avo2-proxy-update-pubdate-qas
  namespace: sc-avo2
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            action_name: update-pubdate
            app: avo2-proxy
            ENV: qas 
            template: cronjob_job
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - "curl -v -X POST -H \"Content-Type: application/json\" -H \"Authorization: Bearer $(PROXY_API_KEY)\" $(HOST)$(PUB_DATE)"
            env:
            envFrom:
            - configMapRef:
                name: proxy-crons-qas
            image: docker-registry.default.svc:5000/sc-avo2/avo2-proxy:qas
            imagePullPolicy: IfNotPresent
            name: avo-crons
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: 0 5 * * *
  successfulJobsHistoryLimit: 3
  suspend: false
